variable "kubeconfig_path" {
  description = "Path to the Talos cluster's kubeconfig, generated by the proxmox-tofu / talosctl bootstrap."
  type        = string
  default     = "../../proxmox-tofu/_out/kubeconfig"
}

variable "namespace" {
  description = "Namespace to install storage-ui into. Must already exist."
  type        = string
  default     = "storage-dev-pub"
}

variable "image_repository" {
  description = "Registry + repository for the storage-ui image (the in-cluster Nexus docker-hosted repo, provisioned in cluster-config)."
  type        = string
  default     = "registry.clusterkeep.dev.net/storage-ui"
}

variable "image_tag" {
  description = "For dev/preview (image_tag_prefix != \"\"): fallback tag, used only if no pushed tag matches image_tag_prefix yet. For prd (image_tag_prefix == \"\"): authoritative on every apply - keep it in sync with the current release tag."
  type        = string
}

variable "image_tag_prefix" {
  description = "Which branch's tag channel this environment tracks: \"DEV-\" or \"PREVIEW-\". \"\" (prd) disables the auto-latest-tag lookup, since release tags are vX.Y.Z, not plain-numeric."
  type        = string
  default     = "DEV-"
}

variable "ingress_hostname" {
  description = "Hostname the storage-ui UI will be served on via Ingress."
  type        = string
  default     = "storage-dev.clusterkeep.dev.net"
}

variable "ingress_enabled" {
  description = "Whether to create a LAN Ingress for this instance. Disable for prd - it's reached only via the Cloudflare Tunnel, and an Ingress would collide with the dev instance's hostname."
  type        = bool
  default     = true
}

variable "image_pull_secret_name" {
  description = "Name of the imagePullSecret to use, if the Nexus docker-hosted repo requires auth. Leave blank if the repo allows anonymous pulls."
  type        = string
  default     = ""
}

variable "auth_api_base_url" {
  description = "auth-api URL storage-ui checks the ck_sso session cookie against on every request."
  type        = string
  default     = "https://auth-dev.clusterkeep.dev.net"
}

variable "auth_api_internal_url" {
  description = "In-cluster Service URL for auth-api. Used for this backend's own server-to-server session check -- the public hostname above only resolves for browsers, not pods."
  type        = string
  default     = "http://auth-api.clusterkeep-dev-priv.svc.cluster.local"
}

variable "clusterkeep_ui_base_url" {
  description = "clusterkeep-ui URL an unauthenticated visitor is redirected to."
  type        = string
  default     = "https://dev.clusterkeep.dev.net"
}
