name: build

on:
  push:
    branches: [development, preview, main]
  workflow_dispatch:

concurrency:
  group: tofu-storage-ui
  cancel-in-progress: false

jobs:
  build:
    uses: ha-private-cloud/pipelines/.github/workflows/app-build.yml@main
    with:
      app: storage-ui
